// @routes-hash 3cfad40b3c8658b442ab766a9323d740
import { Express } from "express";

import route1 from "./routes/assets/addAssets";
import route2 from "./routes/assets/delAssets";
import route3 from "./routes/assets/generateAssets";
import route4 from "./routes/assets/getAssets";
import route5 from "./routes/assets/getImage";
import route6 from "./routes/assets/getStoryboard";
import route7 from "./routes/assets/polishPrompt";
import route8 from "./routes/assets/saveAssets";
import route9 from "./routes/assets/updateAssets";
import route10 from "./routes/assets/delImage";
import route11 from "./routes/assets/updateImage";
import route12 from "./routes/index/index";
import route13 from "./routes/novel/addNovel";
import route14 from "./routes/novel/delNovel";
import route15 from "./routes/novel/getNovel";
import route16 from "./routes/novel/updateNovel";
import route17 from "./routes/other/clearDatabase";
import route18 from "./routes/other/deleteAllData";
import route19 from "./routes/other/getCaptcha";
import route20 from "./routes/other/login";
import route21 from "./routes/other/testAI";
import route22 from "./routes/other/testImage";
import route23 from "./routes/other/testVideo";
import route24 from "./routes/outline/addOutline";
import route25 from "./routes/outline/agentsOutline";
import route26 from "./routes/outline/delOutline";
import route27 from "./routes/outline/getHistory";
import route28 from "./routes/outline/getOutline";
import route29 from "./routes/outline/getPartScript";
import route30 from "./routes/outline/getStoryline";
import route31 from "./routes/outline/setHistory";
import route32 from "./routes/outline/updateOutline";
import route33 from "./routes/outline/updateScript";
import route34 from "./routes/outline/updateStoryline";
import route35 from "./routes/project/addProject";
import route36 from "./routes/project/delProject";
import route37 from "./routes/project/getProject";
import route38 from "./routes/project/getProjectCount";
import route39 from "./routes/project/getSingleProject";
import route40 from "./routes/project/updateProject";
import route41 from "./routes/prompt/getPrompts";
import route42 from "./routes/prompt/updatePrompt";
import route43 from "./routes/script/generateScriptApi";
import route44 from "./routes/script/generateScriptSave";
import route45 from "./routes/script/geScriptApi";
import route46 from "./routes/setting/addModel";
import route47 from "./routes/setting/configurationModel";
import route48 from "./routes/setting/delModel";
import route49 from "./routes/setting/getAiModelMap";
import route50 from "./routes/setting/getLog";
import route51 from "./routes/setting/getSetting";
import route52 from "./routes/setting/getVideoModelList";
import route53 from "./routes/setting/updateModel";
import route54 from "./routes/setting/updeteModel";
import route55 from "./routes/storyboard/batchSuperScoreImage";
import route56 from "./routes/storyboard/chatStoryboard";
import route57 from "./routes/storyboard/generateShotImage";
import route58 from "./routes/storyboard/generateStoryboardApi";
import route59 from "./routes/storyboard/generateVideoPrompt";
import route60 from "./routes/storyboard/getStoryboard";
import route61 from "./routes/storyboard/keepStoryboard";
import route62 from "./routes/storyboard/saveStoryboard";
import route63 from "./routes/storyboard/uploadImage";
import route64 from "./routes/task/getTaskApi";
import route65 from "./routes/task/taskDetails";
import route66 from "./routes/user/getUser";
import route67 from "./routes/video/addVideo";
import route68 from "./routes/video/addVideoConfig";
import route69 from "./routes/video/deleteVideoConfig";
import route70 from "./routes/video/generatePrompt";
import route71 from "./routes/video/generateVideo";
import route72 from "./routes/video/getManufacturer";
import route73 from "./routes/video/getVideo";
import route74 from "./routes/video/getVideoConfigs";
import route75 from "./routes/video/getVideoModel";
import route76 from "./routes/video/getVideoStoryboards";
import route77 from "./routes/video/reviseVideoStoryboards";
import route78 from "./routes/video/saveVideo";
import route79 from "./routes/video/upDateVideoConfig";

export default async (app: Express) => {
  const wsPrefix = process.env.WS_PREFIX || "/ws";
  const shouldAddPrefix = wsPrefix !== "/";
  
  app.use("/assets/addAssets", route1);
  app.use("/assets/delAssets", route2);
  app.use("/assets/generateAssets", route3);
  app.use("/assets/getAssets", route4);
  app.use("/assets/getImage", route5);
  app.use("/assets/getStoryboard", route6);
  app.use("/assets/polishPrompt", route7);
  app.use("/assets/saveAssets", route8);
  app.use("/assets/updateAssets", route9);
  app.use("/assets/delImage", route10);
  app.use("/assets/updateImage", route11);
  app.use("/index", route12);
  app.use("/novel/addNovel", route13);
  app.use("/novel/delNovel", route14);
  app.use("/novel/getNovel", route15);
  app.use("/novel/updateNovel", route16);
  app.use("/other/clearDatabase", route17);
  app.use("/other/deleteAllData", route18);
  app.use("/other/getCaptcha", route19);
  app.use("/other/login", route20);
  app.use("/other/testAI", route21);
  app.use("/other/testImage", route22);
  app.use("/other/testVideo", route23);
  app.use("/outline/addOutline", route24);
  app.use(shouldAddPrefix ? `${wsPrefix}/outline/agentsOutline` : "/outline/agentsOutline", route25);
  app.use("/outline/delOutline", route26);
  app.use("/outline/getHistory", route27);
  app.use("/outline/getOutline", route28);
  app.use("/outline/getPartScript", route29);
  app.use("/outline/getStoryline", route30);
  app.use("/outline/setHistory", route31);
  app.use("/outline/updateOutline", route32);
  app.use("/outline/updateScript", route33);
  app.use("/outline/updateStoryline", route34);
  app.use("/project/addProject", route35);
  app.use("/project/delProject", route36);
  app.use("/project/getProject", route37);
  app.use("/project/getProjectCount", route38);
  app.use("/project/getSingleProject", route39);
  app.use("/project/updateProject", route40);
  app.use("/prompt/getPrompts", route41);
  app.use("/prompt/updatePrompt", route42);
  app.use("/script/generateScriptApi", route43);
  app.use("/script/generateScriptSave", route44);
  app.use("/script/geScriptApi", route45);
  app.use("/setting/addModel", route46);
  app.use("/setting/configurationModel", route47);
  app.use("/setting/delModel", route48);
  app.use("/setting/getAiModelMap", route49);
  app.use("/setting/getLog", route50);
  app.use("/setting/getSetting", route51);
  app.use("/setting/getVideoModelList", route52);
  app.use("/setting/updateModel", route53);
  app.use("/setting/updeteModel", route54);
  app.use("/storyboard/batchSuperScoreImage", route55);
  app.use(shouldAddPrefix ? `${wsPrefix}/storyboard/chatStoryboard` : "/storyboard/chatStoryboard", route56);
  app.use("/storyboard/generateShotImage", route57);
  app.use("/storyboard/generateStoryboardApi", route58);
  app.use("/storyboard/generateVideoPrompt", route59);
  app.use("/storyboard/getStoryboard", route60);
  app.use("/storyboard/keepStoryboard", route61);
  app.use("/storyboard/saveStoryboard", route62);
  app.use("/storyboard/uploadImage", route63);
  app.use("/task/getTaskApi", route64);
  app.use("/task/taskDetails", route65);
  app.use("/user/getUser", route66);
  app.use("/video/addVideo", route67);
  app.use("/video/addVideoConfig", route68);
  app.use("/video/deleteVideoConfig", route69);
  app.use("/video/generatePrompt", route70);
  app.use("/video/generateVideo", route71);
  app.use("/video/getManufacturer", route72);
  app.use("/video/getVideo", route73);
  app.use("/video/getVideoConfigs", route74);
  app.use("/video/getVideoModel", route75);
  app.use("/video/getVideoStoryboards", route76);
  app.use("/video/reviseVideoStoryboards", route77);
  app.use("/video/saveVideo", route78);
  app.use("/video/upDateVideoConfig", route79);
}
